/*
 * AttributesPanel.java
 *
 * Created on 30.3.2011, 10:22:55
 */
package net.parostroj.timetable.gui.components;

import java.util.LinkedList;
import java.util.Map;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import net.parostroj.timetable.gui.utils.ResourceLoader;
import net.parostroj.timetable.model.Attributes;

/**
 * Panel with table with attributes.
 *
 * @author jub
 */
public class AttributesPanel extends javax.swing.JPanel {

    private AttributesTableModel attributesTableModel;
    private String category;

    /** Creates new form AttributesPanel */
    public AttributesPanel() {
        initComponents();
        attributesTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    removeButton.setEnabled(attributesTable.getSelectedRow() != -1);
                }
            }
        });
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategory() {
        return category;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        attributesTable = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        attributesTable.setModel(new net.parostroj.timetable.gui.components.AttributesTableModel(category));
        attributesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane.setViewportView(attributesTable);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addButton.setText(ResourceLoader.getString("button.new")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(addButton);

        nameTextField.setColumns(20);
        nameTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nameTextFieldCaretUpdate(evt);
            }
        });
        buttonsPanel.add(nameTextField);

        removeButton.setText(ResourceLoader.getString("button.delete")); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(removeButton);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (this.attributesTableModel != null) {
            this.attributesTableModel.getAttributes().set(nameTextField.getText(), "", category);
        }
        nameTextField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int row = attributesTable.getSelectedRow();
        if (row != -1) {
            String name = attributesTableModel.getUserNames().get(row);
            attributesTableModel.getAttributes().remove(name, category);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void nameTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nameTextFieldCaretUpdate
        addButton.setEnabled(!"".equals(nameTextField.getText()));
    }//GEN-LAST:event_nameTextFieldCaretUpdate

    public void startEditing(Attributes attributes) {
        attributesTableModel = new AttributesTableModel(category);
        attributesTableModel.startEditing(attributes);
        attributesTable.setModel(attributesTableModel);
        this.updateColumns();
        nameTextField.setText("");
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
    }

    public Attributes stopEditing() {
        Attributes attributes = attributesTableModel.stopEditing();
        attributesTableModel = null;
        attributesTable.setModel(new DefaultTableModel());
        return attributes;
    }
    
    private void updateColumns() {
        TableColumn nameColumn = attributesTable.getColumnModel().getColumn(0);
        nameColumn.setMaxWidth(200);
        nameColumn.setPreferredWidth(100);
    }
    
    public Attributes getAttributes() {
        return attributesTableModel.getAttributes();
    }
    
    public static void updateAttributes(Attributes to, Attributes from, String category) {
        Map<String, Object> fromMap = from.getAttributesMap(category); 
        Map<String, Object> toMap = to.getAttributesMap(category); 
        // update modified ...
        for (String name : fromMap.keySet()) {
            if ((fromMap.get(name) != null && !fromMap.get(name).equals(toMap.get(name)))
                    || (fromMap.get(name) == null && toMap.get(name) != null)){
                to.set(name, fromMap.get(name), category);
            }
        }
        // remove deleted
        for (String name : new LinkedList<String>(toMap.keySet())) {
            if (!fromMap.containsKey(name)) {
                to.remove(name, category);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable attributesTable;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
