/*
 * CirculationView.java
 *
 * Created on 22.6.2011, 13:44:02
 */
package net.parostroj.timetable.gui.components;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.Collection;

import net.parostroj.timetable.model.TrainDiagram;
import net.parostroj.timetable.model.TrainsCycle;
import net.parostroj.timetable.model.TrainsCycleType;

/**
 * View with circulations of certain type.
 *
 * @author jub
 */
public class CirculationView extends javax.swing.JPanel {

    private static TrainsCycleType TYPE = TrainsCycleType.DRIVER_CYCLE; 

    private TrainDiagram diagram;

    /** Creates new form CirculationView */
    public CirculationView() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (diagram != null) {
            paintCirculations((Graphics2D) g, diagram.getCycles(TYPE));
        }
    }

    public void setDiagram(TrainDiagram diagram) {
        this.diagram = diagram;
        this.repaint();
    }
    
    private void paintCirculations(Graphics2D g, Collection<TrainsCycle> circulations) {
        Rectangle2D bounds = g.getFont().getStringBounds("M", g.getFontRenderContext());
        int start = 0;
        for (TrainsCycle circulation : circulations) {
            start += bounds.getHeight();
            paintCirculation(g, circulation, new Point((int)bounds.getWidth(), start));
        }
    }
    
    private void paintCirculation(Graphics2D g, TrainsCycle circulation, Point2D position) {
        g.drawString(circulation.getName(), (int)position.getX(), (int)position.getY());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void circulationRemoved(TrainsCycle circulation) {
        this.repaint();
    }

    public void circulationAdded(TrainsCycle circulation) {
        this.repaint();
    }

    public void circulationUpdated(TrainsCycle circulation) {
        this.repaint();
    }
}
