package net.parostroj.timetable.gui.components;

import java.awt.Font;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import net.parostroj.timetable.model.GrafikonException;
import net.parostroj.timetable.model.Script;
import net.parostroj.timetable.model.Script.Language;

/**
 * Editing component for scripts.
 *
 * @author jub
 */
public class ScriptEditBox extends javax.swing.JPanel {

    /** Creates new form ScriptEditBox */
    public ScriptEditBox() {
        initComponents();

        for (Language language : Language.values()) {
            languageComboBox.addItem(language);
        }

        Border border = new CompoundBorder(new EmptyBorder(5, 5, 0, 5), scrollPane.getBorder());
        scrollPane.setBorder(border);
    }

    public void setColumns(int columns) {
        scriptTextArea.setColumns(columns);
    }

    public int getColumns() {
        return scriptTextArea.getColumns();
    }

    public void setRows(int rows) {
        scriptTextArea.setRows(rows);
    }

    public int getRows() {
        return scriptTextArea.getRows();
    }

    public void setScriptFont(Font font) {
        scriptTextArea.setFont(font);
    }

    public Font getScriptFont() {
        return scriptTextArea.getFont();
    }

    public String getScriptText() {
        return scriptTextArea.getText();
    }

    public void setScriptText(String text) {
        scriptTextArea.setText(text);
    }
    
    public Language getScriptLanguage() {
        return (Language) languageComboBox.getSelectedItem();
    }

    public void setScriptLanguage(Language language) {
        languageComboBox.setSelectedItem(language);
    }

    public Script getScript() throws GrafikonException {
        return Script.createScript(getScriptText(), getScriptLanguage());
    }

    public void setScript(Script script) {
        if (script != null) {
            setScriptText(script.getSourceCode());
            setScriptLanguage(script.getLanguage());
        } else {
            setScriptText("");
            setScriptLanguage(Language.GROOVY);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        scriptTextArea = new javax.swing.JTextArea();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        languageComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setViewportView(scriptTextArea);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        panel.add(languageComboBox);

        add(panel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox languageComboBox;
    private javax.swing.JTextArea scriptTextArea;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
