/*
 * NetView.java
 *
 * Created on 24. srpen 2007, 9:09
 */
package net.parostroj.timetable.gui.views;

import java.awt.Rectangle;
import java.awt.geom.Rectangle2D;
import java.util.HashMap;
import java.util.Map;
import net.parostroj.timetable.gui.*;
import net.parostroj.timetable.model.*;
import org.jgraph.event.GraphModelEvent;
import org.jgrapht.ext.JGraphModelAdapter;
import org.jgraph.JGraph;
import org.jgraph.event.GraphModelListener;
import org.jgraph.graph.*;

/**
 * Net view ....
 * 
 * @author jub
 */
public class NetView extends javax.swing.JPanel implements ApplicationModelListener, GraphModelListener {
    
    private JGraphModelAdapter<Node,Line> netAdapter;
    
    private ApplicationModel model;
    
    private JGraph jGraph;

    public NetView() {
        initComponents();
        GraphModel m = new DefaultGraphModel();
        jGraph = new JGraph(m);
        this.add(jGraph);
        jGraph.setEditable(false);
        jGraph.setConnectable(false);
        jGraph.setSizeable(false);
        jGraph.setDisconnectable(false);
        jGraph.setEdgeLabelsMovable(false);
        jGraph.getSelectionModel().setSelectionMode(GraphSelectionModel.SINGLE_GRAPH_SELECTION);
    }

    public void setNetEditModel(NetSelectionModel netEditModel) {
        jGraph.addGraphSelectionListener(netEditModel);
    }
    
    public void setModel(ApplicationModel model) {
        this.model = model;
        this.model.addListener(this);
        this.setNet(model);
    }

    @Override
    public void modelChanged(ApplicationModelEvent event) {
        switch (event.getType()) {
        case SET_DIAGRAM_CHANGED:
            if (model.getDiagram() != null) {
                this.setNet(model);
            }
            break;
        case MODIFIED_NODE:
            // redraw node
            this.updateNode((Node)event.getObject());
            break;
        case MODIFIED_LINE:
            // redraw line
            this.updateLine((Line)event.getObject());
            break;
        }
    }

    @Override
    public void graphChanged(GraphModelEvent event) {
        for (Object o : event.getChange().getChanged()) {
            if (!(o instanceof DefaultGraphCell))
                continue;
            DefaultGraphCell cell = (DefaultGraphCell)o;
            if (!(cell.getUserObject() instanceof Node))
                continue;
            Node node = (Node)cell.getUserObject();
            if (node == null)
                continue;
            Map attr = cell.getAttributes();
            Rectangle2D b = GraphConstants.getBounds(attr);
            if (!callChange) {
                node.setPositionX(b.getBounds().x);
                node.setPositionY(b.getBounds().y);
            }
        }
    }
    
    private void setNet(ApplicationModel model) {
        if (model.getDiagram() != null) {
            this.setNet(model.getDiagram().getNet());
        } else {
            this.setNet((Net)null);
        }
    }

    private void setNet(Net net) {
        if (net == null) {
            jGraph.setModel(new DefaultGraphModel());
            return;
        }
        
        // remove listener
        jGraph.getModel().removeGraphModelListener(this);
        jGraph.getSelectionModel().clearSelection();
        
        // initialize adapter
        netAdapter = new JGraphModelAdapter<Node, Line>(net.getGraph());
        jGraph.setModel(netAdapter);
        
        for (Node point : net.getNodes()) {
            this.positionVertexAt(point, point.getPositionX(), point.getPositionY());
        }

        // set listener afterwards to not receive event of initial placement
        netAdapter.addGraphModelListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void positionVertexAt(Object vertex, int x, int y) {
        DefaultGraphCell cell = netAdapter.getVertexCell(vertex);
        Map attr = cell.getAttributes();
        Rectangle2D b = GraphConstants.getBounds(attr);

        GraphConstants.setBounds(attr, new Rectangle(x, y, (int) b.getWidth(), (int) b.getHeight()));

        Map<GraphCell, Map> cellAttr = new HashMap<GraphCell, Map>();
        cellAttr.put(cell, attr);
        netAdapter.edit(cellAttr, null, null, null);
    }

    private boolean callChange = false;

    private void updateNode(Node node) {
        callChange = true;
        netAdapter.cellsChanged(new Object[]{netAdapter.getVertexCell(node)});
        callChange = false;
    }

    private void updateLine(Line line) {
        callChange = true;
        netAdapter.cellsChanged(new Object[]{netAdapter.getEdgeCell(line)});
        callChange = false;
    }
}
