/*
 * ECDetailsView.java
 *
 * Created on 12. září 2007, 15:18
 */
package net.parostroj.timetable.gui.views;

import net.parostroj.timetable.gui.ApplicationModel;
import net.parostroj.timetable.gui.ApplicationModelEvent;
import net.parostroj.timetable.gui.ApplicationModelListener;
import net.parostroj.timetable.model.TrainsCycle;
import net.parostroj.timetable.utils.ResourceLoader;

/**
 * View with details about selected engine cycle.
 * 
 * @author jub
 */
public class TCDetailsView extends javax.swing.JPanel implements ApplicationModelListener {
    
    private ApplicationModel model;
    
    private TCDelegate delegate;
    
    /** Creates new form ECDetailsView */
    public TCDetailsView() {
        initComponents();
    }
    
    public void setModel(ApplicationModel model, TCDelegate delegate) {
        model.addListener(this);
        this.model = model;
        this.delegate = delegate;
    }

    @Override
    public void modelChanged(ApplicationModelEvent event) {
        TCDelegate.Action action = delegate.transformEventType(event.getType());
        if (action != null)
            switch (action) {
                case SELECTED_CHANGED:
                    this.updateValues((TrainsCycle)event.getObject());
                    break;
            }
    }
    
    private void updateValues(TrainsCycle cycle) {
        if (cycle == null) {
            nameTextField.setText("");
            commentTextField.setText("");
            descriptionTextField.setText("");
        } else {
            nameTextField.setText(cycle.getName());
            commentTextField.setText((String)cycle.getAttribute("comment"));
            descriptionTextField.setText(cycle.getDescription());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        javax.swing.JLabel nameLabel = new javax.swing.JLabel();
        javax.swing.JLabel descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        javax.swing.JLabel commentLabel = new javax.swing.JLabel();
        commentTextField = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();

        nameTextField.setEditable(false);

        nameLabel.setText(ResourceLoader.getString("ec.details.name")); // NOI18N

        descriptionLabel.setText(ResourceLoader.getString("ec.details.description")); // NOI18N

        commentLabel.setText(ResourceLoader.getString("ec.details.comment")); // NOI18N

        commentTextField.setEditable(false);

        changeButton.setText(ResourceLoader.getString("ec.details.change")); // NOI18N
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(descriptionLabel)
                    .addComponent(commentLabel))
                .addContainerGap(352, Short.MAX_VALUE))
            .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(commentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
    // set values for cycle
    TrainsCycle cycle = delegate.getSelectedCycle(model);
    if (cycle != null) {
        cycle.setDescription(descriptionTextField.getText());
        cycle.setAttribute("comment", commentTextField.getText());
    }
}//GEN-LAST:event_changeButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField commentTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
}
