/*
 * CreateTrainDialog.java
 *
 * Created on 3. září 2007, 19:49
 */
package net.parostroj.timetable.gui.dialogs;

import net.parostroj.timetable.gui.ApplicationModel;
import net.parostroj.timetable.model.Group;
import net.parostroj.timetable.utils.ResourceLoader;

/**
 * Create train dialog.
 *
 * @author jub
 */
public class CreateTrainDialog extends javax.swing.JDialog {

    /**
     * Creates new form CreateTrainDialog.
     *
     * @param parent parent window
     * @param model model
     */
    public CreateTrainDialog(java.awt.Frame parent, ApplicationModel model) {
        super(parent, true);
        initComponents();
        createTrainView.setModel(model);

        // fix size
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createTrainView = new net.parostroj.timetable.gui.views.CreateTrainView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ResourceLoader.getString("dialog.createtrain.title")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTrainView, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTrainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.parostroj.timetable.gui.views.CreateTrainView createTrainView;
    // End of variables declaration//GEN-END:variables

    public void updateView(Group selectedGroup) {
        createTrainView.updateView(selectedGroup);
    }
}
