/*
 * StatusBar.java
 *
 * Created on 4. září 2007, 16:54
 */
package net.parostroj.timetable.gui;

import net.parostroj.timetable.utils.ResourceLoader;
import java.awt.BorderLayout;

/**
 * Status bar for the application.
 *
 * @author jub
 */
public class StatusBar extends javax.swing.JPanel implements ApplicationModelListener {

    /** Creates new form StatusBar */
    public StatusBar() {
        initComponents();
    }

    @Override
    public void modelChanged(ApplicationModelEvent event) {
        switch (event.getType()) {
            case SET_DIAGRAM_CHANGED:
                if (event.getModel().getDiagram() != null)
                    left.setText(ResourceLoader.getString("status.bar.trains") + " " + event.getModel().getDiagram().getTrains().size());
                else
                    left.setText("");
                break;
            default:
                // nothings
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JTextField();
        left.setColumns(15);
        center = new javax.swing.JTextField();
        right = new javax.swing.JTextField();
        right.setColumns(15);

        left.setEditable(false);

        center.setEditable(false);

        right.setEditable(false);
        setLayout(new BorderLayout(0, 0));
        add(left, BorderLayout.WEST);
        add(center, BorderLayout.CENTER);
        add(right, BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField center;
    private javax.swing.JTextField left;
    private javax.swing.JTextField right;
    // End of variables declaration//GEN-END:variables

}
