/*
 * NetPane.java
 *
 * Created on 3. září 2007, 14:44
 */
package net.parostroj.timetable.gui.panes;

import net.parostroj.timetable.gui.ApplicationModel;

/**
 * Net editing pane.
 *
 * @author jub
 */
public class NetPane extends javax.swing.JPanel {
    
    /** Creates new form NetPane */
    public NetPane() {
        initComponents();
    }
    
    public void setModel(ApplicationModel model) {
        netEditView.setModel(model);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        netEditView = new net.parostroj.timetable.gui.views.NetEditView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(netEditView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(netEditView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.parostroj.timetable.gui.views.NetEditView netEditView;
    // End of variables declaration//GEN-END:variables
    
}
