name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jpackage jpackageImageZip distribution
